name: Update SSK Data

on:
  push:
  schedule:
    # Runs the job every minute
    - cron: "* * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # Checkout the repository to access the files
    - uses: actions/checkout@v2

    # Setup Node.js environment
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # Install dependencies
    - run: npm ci

    # Run the script to update the files
    - name: Run Update Script
      run: node index.js

    # Update SSK_1.json on GitHub
    - name: Update SSK_1.json on GitHub
      uses: test-room-7/action-update-file@v1
      with:
        file-path: SSK_1.json
        commit-msg: Update SSK_1.json
        github-token: ${{ secrets.GH_TOKEN }}
        branch: main

    # Update SSK_2.json on GitHub
    - name: Update SSK_2.json on GitHub
      uses: test-room-7/action-update-file@v1
      with:
        file-path: SSK_2.json
        commit-msg: Update SSK_2.json
        github-token: ${{ secrets.GH_TOKEN }}
        branch: main

    # Update SSK_3.json on GitHub
    - name: Update SSK_3.json on GitHub
      uses: test-room-7/action-update-file@v1
      with:
        file-path: SSK_3.json
        commit-msg: Update SSK_3.json
        github-token: ${{ secrets.GH_TOKEN }}
        branch: main
